### PR TITLE
Allows specify XML StyleId to be applied in a Table

### PR DESCRIPTION
**Pull request by ramonmata**
Allows user to specify a style Id from imported styles
As specified in table Structure in http://officeopenxml.com/WPtable.php

`<w:tblStyle w:val="TableGrid"/>`

regards,
Ramon

### CODE REVIEW

**Comment by dolanmiu** [comment]
Can you create a demo to showcase this?

**Comment by ramonmata** [comment]
> 
> 
> Can you create a demo to showcase this?

Added `demo/48-table-xml-styles.ts` with sample usage

**Comment by dolanmiu** [comment]
This breaks some other demos

**Comment by ramonmata** [comment]
> 
> 
> This breaks some other demos

Seems to be better now, Hope it helps!
best regards!

**Comment by dolanmiu** [comment]
Thank you! merged in

**Pull request merged**
