### PR TITLE
Fix: `rowSpan` does not work correctly

### PR DESCRIPTION
**Pull request by wangfengming**
Can't get the correct rowSpan table for `table6` in `demo/32-merge-and-shade-table-cells.ts` 

```typescript
const table6 = new Table({
    rows: [
        new TableRow({
            children: [
                new TableCell({
                    children: [new Paragraph("11")],
                }),
                new TableCell({
                    children: [new Paragraph("12")],
                }),
            ],
        }),
        new TableRow({
            children: [
                new TableCell({
                    children: [new Paragraph("21"), new Paragraph("31")],
                    rowSpan: 2,
                }),
                new TableCell({
                    children: [new Paragraph("22")],
                }),
            ],
        }),
        new TableRow({
            children: [
                new TableCell({
                    children: [new Paragraph("32")],
                }),
            ],
        }),
    ],
    width: {
        size: 100,
        type: WidthType.PERCENTAGE,
    },
});
```

expected result:
image

actual result
image

fixes https://github.com/dolanmiu/docx/issues/509
fixes https://github.com/dolanmiu/docx/issues/501
fixes https://github.com/dolanmiu/docx/issues/456

### CODE REVIEW

**Comment by wangfengming** [comment]
https://github.com/dolanmiu/docx/issues/501
https://github.com/dolanmiu/docx/issues/456

**Comment by wangfengming** [comment]
and the continue cell should have the same borders to the first cell
image

**Comment by wangfengming** [comment]
fix https://github.com/dolanmiu/docx/issues/509

**Comment by wangfengming** [comment]
need more test cases?  @dolanmiu

**Comment by wangfengming** [comment]
all done now

**Comment by wangfengming** [comment]
finished
image

**Comment by dolanmiu** [comment]
Should be fine, will review soon

**Comment by dolanmiu** [comment]
There is a problem with Travis CI, saying it's status is "waiting"

I will wait for a while longer. If it persists, I will merge anyway

**Comment by dolanmiu** [comment]
Merged. Thanks

Will create a new version soon

**Pull request merged**
