### PR TITLE
Implement sample version of Comment feature.

### PR DESCRIPTION
**Pull request by chenyuncai**
Implement the comment feature.

add comment-run element.
add document attr config for comment feature.
add content-type and relationships item for comment feature.
add a comment builder demo.
change the packer prettier param to supprort custom prettify string as sometime you can pass two blanks to xml output in develop mode.

### CODE REVIEW

**Comment by chenyuncai** [comment]
@dolanmiu Hi, I have fixed my code about the comments feature PR.

1. Move the comments property to CoreProperies so i can get the comments member field in options and then packer the comments.xml with the data from File.Comments field.
2. Rollback the document template interface modification.
3. Change the packer prettify type to a enum string so we can use the prettify feature safely(I dont think this config field blong to File).

Thanks, this is a great project ^V^.

**Comment by chenyuncai** [comment]
The related last PR : https://github.com/dolanmiu/docx/pull/1440

**Comment by dolanmiu** [comment]
Seems like this demo does not work? Can you confirm?

**Comment by dolanmiu** [comment]
Correction yes, it does work, can confirm

**Pull request merged**
