### PR TITLE
Add Highlight and Shading to the properties

### LINKED ISSUE #305: Is there a highlight function?
In the documentation, I found functions for all (bold,  italic...) the styling options except "Highlighting". Does it have a different name or is it implemented?

Thank you.

### PR DESCRIPTION
**Pull request by mforman1**
#  Add Highlighting and Shading to the the styling options
Styles now has Highlight and Shadow
Closes #305, #309 

#### Highlighting:
`this.doc.Styles.createCharacterStyle('myStyle').highlight('yellow');`
```
this.doc.addParagraph(
    new Paragraph()
      .addRun(
        new TextRun('test')
          .highlight('yellow')
          )
      .right()
  )
```

#### Shading:
`this.doc.Styles.createCharacterStyle('myStyle').shadow('pct10','00FFFF','FF0000');`
```
this.doc.addParagraph(
    new Paragraph()
      .addRun(
        new TextRun('test')
           .shadow('pct10','00FFFF','FF0000')
      )
      .right()
  )
```

#### Highlighting:
The single attribute `color` specifies the color of the text highlighting. Possible values are: `black`, `blue`, `cyan`, `darkBlue`, `darkCyan`, `darkGray`, `darkGreen`, `darkMagenta`, `darkRed`, `darkYellow`, `green`, `lightGray`, `magenta`, `none`, `red`, `white`, `yellow`.

#### Shading:

Attribute | Description
-- | --
fill | Specifies the color to be used for the background. Values are given as hex values (i.e., in RRGGBB format). No `#`, unlike hex values in HTML/CSS. E.g., `fill="FFFF00"`.
color | Specifies the color to be used for any foreground pattern specified with the val attribute. Values are given as hex values (in RRGGBB format). No `#`, unlike hex values in HTML/CSS. E.g., `fill="FFFF00"`.
value | Specifies the pattern to be used to lay the pattern color over the background color. For example, `value="pct10"` indicates that the border style is a 10 percent foreground fill mask. Possible values are: `clear` (no pattern), `pct10`, `pct12`, `pct15` . . ., `diagCross`, `diagStripe`, `horzCross`, `horzStripe`, `nil`, `thinDiagCross`, `solid`, etc. See ECMA-376, 3rd, § 17.18.78 for a complete listing.

### CODE REVIEW

**Comment by dolanmiu** [comment]
Nice work!

Seems like this PR not only has `this.doc.Styles.createCharacterStyle('myStyle').highlight(color);`, but also other ways of highlighting? It seems you can directly add it via the Run

**Comment by mforman1** [comment]
> Nice work!
> 
> Seems like this PR not only has `this.doc.Styles.createCharacterStyle('myStyle').highlight(color);`, but also other ways of highlighting? It seems you can directly add it via the Run

Thanks!
Right, I just gave one example, wherever you can style with `bold()` I added the option to also `highlight()` and `shadow()`.

**Comment by dolanmiu** [comment]
Sweet, merging!

**Comment by mforman1** [comment]
@dolanmiu Thanks for merging!
Have you published to npm?

**Comment by dolanmiu** [comment]
I will do soon, there are a lot of changes in the next release, and I want to do a bit more write up on the documentation first

**Comment by mforman1** [comment]
How soon as soon? We really want to start working with it asap. Perhaps you can publish as an rc in the meantime?

**Comment by dolanmiu** [comment]
I will write up a bit more documentation, then I'll publish tonight.

P.S. I renamed `shadow` to `shading`, I think that was the intended naming by OOXML:

http://officeopenxml.com/WPshading.php

Thanks again!

**Comment by dolanmiu** [comment]
Example of usage in the new API:

https://github.com/dolanmiu/docx/blob/master/demo/46-shading-text.ts

**Comment by dolanmiu** [comment]
Can I ask what company you are at? 

May I put the company on the readme?

**Comment by mforman1** [comment]
Thanks for the example.

Checking out about having the company name on the readme, I'll KYP.

**Comment by mforman1** [comment]
I'm working at Madison CRES, you can put the company name on the readme.

Thanks!

**Comment by bre7** [comment]
highlight should be implemented using shading instead. Custom colors don't work on LibreOffice otherwise.

Works on both:
```xml
<w:shd w:fill="FF6D6D" w:val="clear"/>
```

Doesn't work with LO:
```xml
<w:highlight w:val="FF6D6D"/>
```

**Pull request merged**
