### PR TITLE
FIX: multiple tabStop support for LibreWriter

### PR DESCRIPTION
**Pull request by ronram5126**
Have faced issue with tabStop while using docx.js. Turns out docx generates multiple TabStops with single TabStop. This was not supported by LibreOffice.

So I forked and fixed the issue. I am currently using the fork in my project, will test and update if something else comes up.

Cheers,
Ronit R. BK

### CODE REVIEW

**Comment by ronram5126** [comment]
This fixes issue #1300

**Comment by dolanmiu** [comment]
Thanks for the PR!

I have fixed the prettier and linting errors

I appreciate the effort you made to make it backwards compatiable in the TabStops, but theres no need for that, as it is not exposed to the user, so it will not break the API, we can modify no problem. And that is what I have done. It is much more simple now.

If you can write a demo using the tab stops, that would be great

**Review by dolanmiu — CHANGES_REQUESTED** [review]
Would like you to add a demo to demonstrate this feature please under the `/demo` folder

**Comment by ronram5126** [comment]
@codecov-commenter  I'm busy with work a bit, will do tomorrow. Cheers.

**Comment by ronram5126** [comment]
I have added a demo/75-tab-stops.ts, I hope its fine. Let me know if you need something else.
Cheers.

**Pull request merged**
