### PR TITLE
Added trackChanges key to settings

### LINKED ISSUE #223: Enable "Track Revisions"
I'll submit a PR soon.

Add `w:trackRevisions` flag under settings (https://github.com/dolanmiu/docx/blob/master/src/file/settings/settings.ts ???)

`<w:trackRevisions w:val="true"/>`
or
`<w:trackRevisions w:val="false"/>`

### PR DESCRIPTION
**Pull request by bre7**
Closes #223 

Not 100% sure about Settings. Is this the correct way to add the key ?

### CODE REVIEW

**Comment by dolanmiu** [comment]
Could you call this:

TrackRevisionsComponent

**Comment by dolanmiu** [comment]
Could you fix the tests too

**Comment by bre7** [comment]
> Could you call this:
> 
> TrackRevisionsComponent

👍

I'm not  sure where to include the flag in File's contructor

1. Add it to `IPropertiesOptions`

2. Add it as a new flag
constructor(
        options: IPropertiesOptions = {
            creator: "Un-named",
            revision: "1",
            lastModifiedBy: "Un-named",
        },
        sectionPropertiesOptions: SectionPropertiesOptions = {},
        fileProperties: IFileProperties = {},
        trackRevisions: boolean,
    ) {

**Comment by bre7** [comment]
Still not working correctly. The flag is added to settings.xml but when opened, revision changes isn't enabled.

**Comment by dolanmiu** [comment]
Superseded by https://github.com/dolanmiu/docx/pull/644

**Pull request closed without merging**
