### PR TITLE
fix hyperlink id

### PR DESCRIPTION
**Pull request by Sraleik**
I made this fix for problem with external hyperlink.

related to : #440 #390 

I Could not fix it by passing the proper relationshipCount so i just give a string id for this type of link

### CODE REVIEW

**Comment by dolanmiu** [comment]
Let me check what shortid does, 

I am concerned if all word processors support this, i assumed it had to be an integer number?

`rId0` 'rId6` etc

**Comment by Sraleik** [comment]
I added shortid to fix this quickly. 
I need hyperlink for my Company project very quickly :)

But it could be a custom function that return an random string of n caracter.

i dont think a number is required for relation id, i'v seen `link1` `link2` from word generated document so i'v assumed that any string will do (i might be wrong)

**Comment by dolanmiu** [comment]
Who do you work for? Mind if I add them to the readme?

**Comment by dolanmiu** [comment]
Looks good to me, works fine, merging

**Comment by Sraleik** [comment]
Thanks for the merge :+1: 

I work for Beekast : https://www.beekast.com/
Our current system doesn't use docxjs but next production delivery it will :)

**Comment by dolanmiu** [comment]
Fixes https://github.com/dolanmiu/docx/issues/467

**Pull request merged**
