### PR TITLE
Feature: refine paragraph/run properties options

### PR DESCRIPTION
**Pull request by wangfengming**
https://github.com/dolanmiu/docx/issues/560

- refine paragraph/run properties options
- can set defaults style with DocumentDefaults & RunPropertiesDefaults & ParagraphPropertiesDefaults
- run properties options support `xxxComplexScript`, and `xxxComplexScript` defaults to `xxx`
- `shadow` alias for `shading`
- export `run/properties` and `styles/defaults`

### CODE REVIEW

**Comment by wangfengming** [comment]
- move `IRunStyleOptions` from `styles/style-options` to `paragraph/run/properties` and rename to `IRunStylePropertiesOptions`
- move `IParagraphStyleOptions2` from  `styles/style-options` to `paragraph/properties` and rename to `IParagraphStylePropertiesOptions`
- `SmallCaps` & `Caps` already exists in `paragraph/run/formatting`. So remove `paragraph/run/caps`.

**Comment by dolanmiu** [comment]
Coverage is failing, it is reducing coverage

**Comment by dolanmiu** [comment]
@wangfengming https://travis-ci.org/github/dolanmiu/docx

**Comment by wangfengming** [comment]
> @wangfengming https://travis-ci.org/github/dolanmiu/docx

Because I'v delete so many lines, `(coverage - delete)/(total - delete)` will less than `coverage/total`.

And I'll add more test cases.

**Comment by wangfengming** [comment]
I've add more test cases.
In fact, the modified code is well covered.
I've delete many line of code. Even I add some test cases,`branches` still less than target(88.3<88.57).
So I exclude file `src/import-dotx/import-dotx.ts` to coverage. (This file has no test)

**Comment by dolanmiu** [comment]
> So I exclude file `src/import-dotx/import-dotx.ts` to coverage. (This file has no test)

Thanks, I would like to one day for this feature to be deprecated, very unmaintainable

**Pull request merged**
