### PR TITLE
resubmitting bidi and RTL support with lint fixs

### PR DESCRIPTION
**Pull request by amitm02**

### CODE REVIEW

**Comment by amitm02** [comment]
I've also added the following:
1) support to complex fonts (e.g hebrew, arabic). it mostly means adding the <w:szCs>
http://officeopenxml.com/WPtextFormatting.php
2) support for horizontal alignments for RTL languages. it mostly means updating the <w:jc> to accept "start" and "end". 
http://officeopenxml.com/WPalignment.php

**Comment by dolanmiu** [comment]
can you write a demo in the `/demo` folder to showcase this feature?

**Comment by amitm02** [comment]
done.

**Comment by dolanmiu** [comment]
Perfect :)

**Pull request merged**
