### PR TITLE
method to remove pagebreaks

### PR DESCRIPTION
**Pull request by sergiofm**

### CODE REVIEW

**Comment by dolanmiu** [comment]
For what use-case would this be useful?

**Comment by sergiofm** [comment]
Sometimes, in my logic, I need to remove page breaks from pre-created paragraph.

**Comment by dolanmiu** [comment]
Is it possible to not create the page breaks in the first place?

I just have a weird feeling about this method

What could be next?

```js
paragraph.removeAllText()
```

```js
paragraph.removeAllImages();
```

😂

**Comment by dolanmiu** [comment]
thanks

**Pull request closed without merging**
