### PR TITLE
External hyperlink support

### PR DESCRIPTION
**Pull request by ivanryuu**
Added external hyperlink support based on http://officeopenxml.com/WPhyperlink.php

### CODE REVIEW

**Comment by ivanryuu** [comment]
I wrote a demo file to verify everything worked that I can push. I can also create the doc page for how to use them if needed.

**Comment by dolanmiu** [comment]
Thank you! looks good

**Comment by dolanmiu** [comment]
Will release this today

**Comment by dolanmiu** [comment]
Released `3.5.0`

**Pull request merged**
