### PR TITLE
Styles cleanup

### PR DESCRIPTION
**Pull request by felipeochoa**
As promised, here's another big change set, this time on styles. The changes here are:

* fixed some **linter warnings**. We're down to 41 warnings!! (excluding test files, which have another 200+ :frowning_face:)
* added a **fluent interface** for creating `ParagraphStyle`s
* minor cleanup (move indent.ts to docx/paragraph; fix Underline default value)

The new styles API lets you do the following:

```js
const styles = new docx.Styles();  // This is the container fed to the packer
styles.createParagraphStyle('aside', 'Aside')
    .basedOn('Normal')
    .next('Normal')
    .color('999999')
    .italics()
    .indent(720)
    .spacing({line: 276});

styles.createParagraphStyle('Heading2', 'Heading 2')
    .basedOn("Normal")
    .next("Normal")
    .quickFormat()
    .size(26)
    .bold()
    .underline('double', 'FF0000')
    .spacing({before: 240, after: 120});
```

### CODE REVIEW

**Comment by dolanmiu** [comment]
are you testing this library out after each change? I have no idea if it works

If you can add an article on the wiki on how to create a style, that would be great!

**Comment by felipeochoa** [comment]
Yes! Beyond the unit tests that I've been adding, I'm using it in my own app. I have a small test script that I use as well to make sure the output open in Word, but that's a bit more manual. Happy to include it as an example if you think it would be helpful

**Comment by felipeochoa** [comment]
Hmm. I can't seem to create or edit the wiki. Have you set it to open access? https://help.github.com/articles/changing-access-permissions-for-wikis/

**Comment by dolanmiu** [comment]
You should now be able to edit

**Comment by dolanmiu** [comment]
I'll work on some linting issues tonight too

**Pull request merged**
