### PR TITLE
Added character spacing attribute

### LINKED ISSUE #157: Missing spacing attribute
Is `w:spacing` missing ? I'm talking about _Character Spacing Adjustment_ (rPr) not _Spacing Between Lines and Above/Below Paragraph_ (pPr)

http://www.datypic.com/sc/ooxml/e-w_spacing-2.html

Should be declared in https://github.com/dolanmiu/docx/blob/master/src/file/paragraph/run/formatting.ts

### PR DESCRIPTION
**Pull request by bre7**
Closes #157 

- [x] Added char spacing attribute (_Character Spacing Adjustment (rPr) not Spacing Between Lines and Above/Below Paragraph (pPr)_)
- [x] Added test case

```ts
const style = new ParagraphStyle("myStyleId").characterSpacing(24);
```

Could you bump npm after the merge ?

### CODE REVIEW

**Comment by dolanmiu** [comment]
> Could you bump npm after the merge ?

Sure

**Comment by bre7** [comment]
Let me know if there's something missing btw

**Comment by dolanmiu** [comment]
Merged, its fine, looks good

If you can help write some documentation for it, it would be awesome

**Comment by bre7** [comment]
Sure. In which file would you recommend ? https://github.com/dolanmiu/docx/blob/master/docs/usage/styling-with-js.md ?

**Comment by dolanmiu** [comment]
https://github.com/dolanmiu/docx/blob/master/docs/usage/styling-with-js.md

**Pull request merged**
