### PR TITLE
Override levels impl

### PR DESCRIPTION
**Pull request by anti-the-social**
Bonjour :) 

Finally got some time to take care of this.
Tell me the secret of running tests! :)  Just after polling and `npm i ` you cannot really run `npm test`
I am getting `TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for `

Nevertheless I believe it should work.
I also fixed and added additional tests to this **breaking change** improvements.

This pull request is related to this issue: https://github.com/dolanmiu/docx/issues/1740

### CODE REVIEW

**Comment by anti-the-social** [comment]
Nanoid has critical vulnerability in the older versions, than 4.
I also have doubts that its the reason (just tried `npm i nanoid 3` `npm test`)

**Comment by dolanmiu** [comment]
> Nanoid has critical vulnerability in the older versions, than 4. I also have doubts that its the reason (just tried `npm i nanoid 3` `npm test`)

No it must be, because there is an open PR which only upgrades nanoid from 3 -> 4, and it broke:

https://github.com/dolanmiu/docx/pull/1548

Take a look

**Comment by dolanmiu** [comment]
There is one broken test in the project

**Comment by anti-the-social** [comment]
Fixed failing test - my bad.

And also found after local testing that some tests at `src/file/paragraph/run/comment-run.spec.ts` were failing for me - reason seems to be the timezone. So I've fixed it via specifying full date in `new Date()` creation. 

Now its all good for me too
image

**Pull request merged**
