### PR TITLE
Feature/emphasis mark

### PR DESCRIPTION
**Pull request by wangfengming**
Support Feature
---

- Emphasis mark

Closes https://github.com/dolanmiu/docx/issues/543

### CODE REVIEW

**Comment by wangfengming** [comment]
image

It only works without this commit https://github.com/dolanmiu/docx/commit/08bc069cbf2b18dff21ac11232522f1eb3f79028

**Comment by dolanmiu** [comment]
Thank you, very good PR!

**Comment by wangfengming** [comment]
I wonder when this will be released

**Comment by wangfengming** [comment]
Hi @dolanmiu , when will this to be released for a new version?

**Comment by dolanmiu** [comment]
Thanks for reminding me @wangfengming, I will release this today

**Comment by dolanmiu** [comment]
published 5.2.0

**Pull request merged**
