### PR TITLE
Update numbering.ts

### PR DESCRIPTION
**Pull request by dolanmiu**

### CODE REVIEW

**Comment by wangfengming** [comment]
This seems doesn't work. The generated file cannot be opened.

---

Checkout on this commit https://github.com/dolanmiu/docx/commit/2654799822493edbe4b96af544f6d51c79381f9a
and then:
```bash
npm run prepublishOnly
ts-node demo/1-basic.ts
```
Try to open `My Document.docx`
image

---

Remove the below code
```ts
{
    level: 9,
    format: "bullet",
    text: "\u2726",
    alignment: AlignmentType.LEFT,
    style: {
        paragraph: {
            indent: { left: 720, hanging: 360 },
        },
    },
},
```
and then:
```bash
npm run prepublishOnly
ts-node demo/1-basic.ts
```
The generated file is normal now.
image

---

Word only support 9 levels

image



@dolanmiu @adrielstar

**Comment by wangfengming** [comment]
Microsoft Word for Mac 
Version 16.16.21 (200413)

**Comment by dolanmiu** [comment]
WIll revert

**Comment by dolanmiu** [comment]
Fixed (reverted) and deployed 1.5.1

Apologies for the delay

**Comment by adrielstar** [comment]
is there a way to modify the code so user can us their own Unicode Character?
 That what am looking for. @dolanmiu  @wangfengming

**Comment by wangfengming** [comment]
```typescript
  const doc = new docx.Document({
    numbering: {
      config: [{
        levels: [
          {
            level: 0,
            format: 'bullet',
            text: '+',
            alignment: docx.AlignmentType.LEFT,
            style: {
              paragraph: {
                indent: {left: 720, hanging: 360},
              },
            },
          }
        ],
        reference: 'num-002',
           //  Since I found that the code use `new RegExp(concreteNumbering.reference, 'g')` to replace xml string.
           // The reference should be unique and mustn't be to breaking xml.
      }],
    },
  })

  const paragraph = new docx.Paragraph({
    text: 'Bullet points',
    numbering: {
      reference: 'num-002',
      level: 0,
    },
  })
  doc.addSection({
    children: [paragraph],
  })
```

image

@adrielstar

**Comment by wangfengming** [comment]
Here's the demo.
https://github.com/dolanmiu/docx/blob/master/demo/3-numbering-and-bullet-points.ts

**Comment by adrielstar** [comment]
> demo.
> https://github.com/dolanmiu/docx/blob/master/demo/3-numbering-and-bullet-points.ts

thanks man work perfect

**Pull request merged**
