### PR TITLE
Better conformance to Office Open XML schema

### PR DESCRIPTION
**Pull request by devoidfury**
This was described in detail in issue #947 

Here's the validator setup I'm using, until a suitable JS version is implemented:  
https://github.com/devoidfury/docx-validator

Locally I have a document.xml that is 413881 lines long. On current release (6.0.3), the document has 21709 validation errrors. With these changes, it validates without any errors. I can't provide this document, but validating pretty much anything with tables, images, paragraphs, textruns, headers, footers, etc will show these errors and they're easily reproducible with the demo docs.

There are likely some elements that I missed, which are not in use in my documents, but it's a good first pass on the issue.

### CODE REVIEW

**Comment by dolanmiu** [comment]
This is awesome

Had a glance through, and it looks good

Will review later

**Comment by devoidfury** [comment]
I've got a number of other changes on my fork with internals cleanup, on a branch based on this one. Would you like me to include them in this PR or wait until this one is merged and send additional PRs later?

**Review by dolanmiu — APPROVED** [review]

**Comment by dolanmiu** [comment]
@devoidfury Approved and merged

Could you tell me why the ordering of the `xml components` being added is important?

**Comment by devoidfury** [comment]
Exactly why they decided to do it, I don't know. In all the versions of the schemas I can find, it's just the way they decided to design it. I imagine for most things it really doesn't matter, but in some cases it definitely does.

See for example, the schema for the base abstract type used under `w:pPr` - notice the `<xsd:sequence>` element here - this means items inside it must be in this specific order to conform.
```
  <xsd:complexType name="CT_PPrBase">
    <xsd:sequence>
      <xsd:element name="pStyle" type="CT_String" minOccurs="0"/>
      <xsd:element name="keepNext" type="CT_OnOff" minOccurs="0"/>
      <xsd:element name="keepLines" type="CT_OnOff" minOccurs="0"/>
      <xsd:element name="pageBreakBefore" type="CT_OnOff" minOccurs="0"/>
      <xsd:element name="framePr" type="CT_FramePr" minOccurs="0"/>
      <xsd:element name="widowControl" type="CT_OnOff" minOccurs="0"/>
      <xsd:element name="numPr" type="CT_NumPr" minOccurs="0"/>
      <xsd:element name="suppressLineNumbers" type="CT_OnOff" minOccurs="0"/>
      <xsd:element name="pBdr" type="CT_PBdr" minOccurs="0"/>
      <xsd:element name="shd" type="CT_Shd" minOccurs="0"/>
      <xsd:element name="tabs" type="CT_Tabs" minOccurs="0"/>
      <xsd:element name="suppressAutoHyphens" type="CT_OnOff" minOccurs="0"/>
      <xsd:element name="kinsoku" type="CT_OnOff" minOccurs="0"/>
      <xsd:element name="wordWrap" type="CT_OnOff" minOccurs="0"/>
      <xsd:element name="overflowPunct" type="CT_OnOff" minOccurs="0"/>
      <xsd:element name="topLinePunct" type="CT_OnOff" minOccurs="0"/>
      <xsd:element name="autoSpaceDE" type="CT_OnOff" minOccurs="0"/>
      <xsd:element name="autoSpaceDN" type="CT_OnOff" minOccurs="0"/>
      <xsd:element name="bidi" type="CT_OnOff" minOccurs="0"/>
      <xsd:element name="adjustRightInd" type="CT_OnOff" minOccurs="0"/>
      <xsd:element name="snapToGrid" type="CT_OnOff" minOccurs="0"/>
      <xsd:element name="spacing" type="CT_Spacing" minOccurs="0"/>
      <xsd:element name="ind" type="CT_Ind" minOccurs="0"/>
      <xsd:element name="contextualSpacing" type="CT_OnOff" minOccurs="0"/>
      <xsd:element name="mirrorIndents" type="CT_OnOff" minOccurs="0"/>
      <xsd:element name="suppressOverlap" type="CT_OnOff" minOccurs="0"/>
      <xsd:element name="jc" type="CT_Jc" minOccurs="0"/>
      <xsd:element name="textDirection" type="CT_TextDirection" minOccurs="0"/>
      <xsd:element name="textAlignment" type="CT_TextAlignment" minOccurs="0"/>
      <xsd:element name="textboxTightWrap" type="CT_TextboxTightWrap" minOccurs="0"/>
      <xsd:element name="outlineLvl" type="CT_DecimalNumber" minOccurs="0"/>
      <xsd:element name="divId" type="CT_DecimalNumber" minOccurs="0"/>
      <xsd:element name="cnfStyle" type="CT_Cnf" minOccurs="0" maxOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>
```

Sadly, this is not documented anywhere in the officeopenxml.com site, and is only found in the ECMA-376 reference schemas (see for example, ECMA-376 fifth edition, part one, page 3839, containing a version of the above element type).

https://www.ecma-international.org/publications-and-standards/standards/ecma-376/

**Pull request merged**
