### PR TITLE
Add total number of pages in a section

### LINKED ISSUE #348: Number of Total Pages Per Section
in a doc with multiple sections, is it possible to implement NumberOfTotalPages for each section separately?

### PR DESCRIPTION
**Pull request by mforman1**
#  Total number of pages in a section
Fixes #348 

## _New Behavior_
At the moment, the existing function `numberOfTotalPages` returns the total number of pages in the entire document, 
the new `numberOfTotalPagesSection` function returns the total number of pages **per section**.

## _Examples_

```
const doc = new Document();

const header = doc.createHeader();
header.createParagraph("Header on another page");
const footer = doc.createFooter();
footer.createParagraph("Foo Bar corp. ")
    .center()
    .addRun(new TextRun("Page Number: ").pageNumber())
    .addRun(new TextRun(" to ").numberOfTotalPagesSection());

doc.addSection({
    headers: {
        default: header,
    },
    footers: {
        default: footer,
    },
    pageNumberStart: 1,
    pageNumberFormatType: PageNumberFormat.DECIMAL,
});

```

### CODE REVIEW

**Comment by mforman1** [comment]
Fixed tests, should be good to go. Is there anything else needed?

**Comment by dolanmiu** [comment]
Would need to rename the demo like so:

https://github.com/dolanmiu/docx/tree/master/demo

**Comment by mforman1** [comment]
Updated, sorry, I were working on the previous version.

**Comment by dolanmiu** [comment]
Merged thanks!

**Comment by mbrevda** [comment]
Do you have an ETA for publishing?

**Comment by dolanmiu** [comment]
I want to get this in first:

https://github.com/dolanmiu/docx/pull/381

**Pull request merged**
