### PR TITLE
Restart numbered lists

### PR DESCRIPTION
**Pull request by carole-lavillonniere**
This PR makes it possible to restart the numbering of numbered lists.
In order to do this, we need to:
1) create an abstract and a concrete numbering for each list (even when they use the same levels config) 
2) assign a similar `numId` to each entry of the same list

The numbered lists demo `demo/29-numbered-lists.ts` was updated in order to showcase the feature and this is a screenshot of the resulting doc:
Screenshot 2020-06-25 at 12 11 49

### CODE REVIEW

**Comment by dolanmiu** [comment]
Thanks for this

Could you fix the tests? Then I will review/merge

**Comment by dolanmiu** [comment]
This is great work, i like the results

But I am wondering if there is a way to turn this more declarative

**Comment by BrentFarese** [comment]
Is this PR going to be merged and released anytime soon?  We are working on re-numbering lists too and need this functionality.  Thanks!

**Comment by BrentFarese** [comment]
@carole-lavillonniere or anyone else on this thread, does anyone know of a current workaround while this PR is still outstanding and not released?  Or, do we have to wait for this PR to have lists without consecutive numbering as shown in the example in the first comment?  Thanks!

**Comment by dolanmiu** [comment]
Yes, it is a good PR, however, it has a breaking change, was wanting to wait until v6 for it to be merged.

**Comment by JosephFoti** [comment]
Hey @dolanmiu, I love the package, but to implement it in my app I really need to be able to reset numbering. Do you have any ideas on a work around for now? Or perhaps an ETA on when v6 will be released? Thanks so much for this, its a huge improvement on what I was working with before.

**Comment by firstnoodle** [comment]
I also desperately need this "feature" - it is my only bug before launch 🤞
Otherwise really happy with the package. Thanks for your work @dolanmiu

**Comment by dolanmiu** [comment]
> I also desperately need this "feature" - it is my only bug before launch 🤞
> Otherwise really happy with the package. Thanks for your work @dolanmiu

Yes, I am working on this now, for the v6 launch

**Comment by dolanmiu** [comment]
Closing this as I cannot work on it because I do not have permission on the branch,

Opening this instead:

https://github.com/dolanmiu/docx/pull/812

**Pull request closed without merging**
