### PR TITLE
Feat/table of contents

### PR DESCRIPTION
**Pull request by sergiofm**
Functionality for creation of Table of Contents.

### CODE REVIEW

**Comment by sergiofm** [comment]
Please take a look at the documentation. I wrote it based on the ooxml documentation, but I don't know if it will be enough for the end users. But, we can release like that and improve if people start to complain. :D

**Comment by dolanmiu** [comment]
Ok, will check documentation. Been reading the code so far

**Comment by dolanmiu** [comment]
Made some changes to the documentation

I want to change the API a little bit if thats ok for the `TableOfContentsProperties`

**Comment by sergiofm** [comment]
Sure! Go ahead!

**Comment by dolanmiu** [comment]
Merged :)

Good work

**Comment by sergiofm** [comment]
Nice! I'll take a look.

**Pull request merged**
