### PR TITLE
Multiple columns in a section

### PR DESCRIPTION
**Pull request by zahrafali**

### CODE REVIEW

**Comment by zahrafali** [comment]
addSection inserts stuff in a new page, is there a way we can have multiple sections in a single page?

**Comment by dolanmiu** [comment]
Thanks! I will review this tomorrow

**Comment by dolanmiu** [comment]
Looks good

The API may change though, but I will tweak this and update the demo before making another release

**Comment by dolanmiu** [comment]
> addSection inserts stuff in a new page, is there a way we can have multiple sections in a single page?

I am not sure actually, will need to investigate

**Comment by zahrafali** [comment]
> Looks good
> 
> The API may change though, but I will tweak this and update the demo before making another release
> 
> Thinking more of a:
> 
> ```ts
> doc.addSection({
>     column: {
>         width: 708,
>         count: 2,
>     }
> });
> ```

Yeah, this looks good

**Comment by zahrafali** [comment]
> > addSection inserts stuff in a new page, is there a way we can have multiple sections in a single page?
> 
> I am not sure actually, will need to investigate

Okay, I will also investigate and see if I can fix it. What I've observed is, when we use addSection, it adds a new section to the document in a new page.

**Comment by dolanmiu** [comment]
Released in `5.0.0-rc4`

**Pull request merged**
