### PR TITLE
Support footnotes on TextRun elements

### LINKED ISSUE #432: Support footnotes on TextRun
## Feature Request

This is a feature request for supporting footnote references on the TextRun element.

## Usecase: 

We ran into the problem, that Paragraphs with mutliple text parts cannot be referenced by footnotes. It would be super handy, to being able to use the `referenceFootnote` function on a TextRun element.

**PS**: Thank you for creating this awesome lib. Works really well 🙌

### PR DESCRIPTION
**Pull request by zaunermax**
This PR implements the possibility to reference footnotes on TextRun elements.

closes #432

### CODE REVIEW

**Comment by jamesmontalvo3** [comment]
@dolanmiu may prefer you to write this declaratively, so rather than adding a method to TextRun objects, instead pass in footnote IDs along with the `ITextRunOptions` object used to instantiate TextRuns.

**Comment by dolanmiu** [comment]
Thanks!

**Comment by dolanmiu** [comment]
> @dolanmiu may prefer you to write this declaratively, so rather than adding a method to TextRun objects, instead pass in footnote IDs along with the `ITextRunOptions` object used to instantiate TextRuns.

Yes

I will refactor this for sure before releasing the next version

**Comment by zaunermax** [comment]
Oh yeah, I just read the issues and discussions on how to keep this lib more declarative, which i generally like! I just wanted to keep it consistent with the paragraph element so I didn't look any further than that. 

Future PRs will keep in mind that declarative > imperative style especially in this usecase.

If you want I can try to transform the API to a declarative style if you want.

**Comment by dolanmiu** [comment]
> If you want I can try to transform the API to a declarative style if you want.

Sure, if you can change it that would be great!

**Pull request merged**
